<?php
require_once 'includes/components.php'; require_once 'config.php'; require_once 'booking_repository.php'; ensureBookingSchema($conn);
$r=$conn->query("SELECT name,target_group,price FROM products WHERE COALESCE(is_active,1)=1 ORDER BY name"); $products=$r?$r->fetch_all(MYSQLI_ASSOC):[];
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Đặt lịch | NALI</title><link rel="stylesheet" href="common.css">
    <link rel="stylesheet" href="dental-theme.css"><link rel="stylesheet" href="content-pages.css"><style>.bw{max-width:800px;margin:38px auto 70px;padding:0 18px}.p{display:flex;gap:8px}.p span{flex:1;padding:10px;text-align:center;background:#e5eef2;border-radius:8px}.p .on{background:#147db0;color:#fff}.s{display:none}.s.on{display:block}.choices,.slots{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.choices label,.slots button{border:1px solid #b8d1dd;padding:12px;border-radius:10px;background:#fff}.slots button:disabled{opacity:.4}.nav{display:flex;justify-content:space-between;margin-top:22px}.nav button{padding:12px 18px;border:0;border-radius:9px;background:#147db0;color:white;font-weight:bold}@media(max-width:600px){.choices,.slots{grid-template-columns:repeat(2,1fr)}}</style></head><body>
<?php renderHeader('contact'); ?>
<main class="bw"><h1>Đặt lịch tư vấn</h1><p>Chọn dịch vụ → giờ còn trống → thông tin liên hệ.</p><div class="p"><span class="on">1. Dịch vụ</span><span>2. Thời gian</span><span>3. Liên hệ</span></div>
<form id="booking-form"><section class="s on"><div class="choices"><?php foreach($products as $x): ?><label><input type="radio" name="service" value="<?=htmlspecialchars($x['name'],ENT_QUOTES)?>" data-group="<?=htmlspecialchars($x['target_group'],ENT_QUOTES)?>"><b><?=htmlspecialchars($x['name'])?></b><br><small><?=number_format((float)$x['price'],0,',','.')?>đ</small></label><?php endforeach; ?></div><label>Mã ưu đãi <input id="booking-code" maxlength="40"></label><div class="nav"><i></i><button type="button" data-next>Tiếp</button></div></section>
<section class="s"><label>Ngày hẹn <input id="booking-date" type="date" min="<?=date('Y-m-d')?>"></label><p id="slot-info">Chọn ngày để xem giờ còn trống.</p><div class="slots" id="slot-grid"></div><input id="booking-time" type="hidden"><div class="nav"><button type="button" data-back>Quay lại</button><button type="button" data-next>Tiếp</button></div></section>
<section class="s"><label>Họ tên <input id="booking-name" required></label><label>Số điện thoại <input id="booking-phone" pattern="0[0-9]{9}" required></label><label>Email <input id="booking-email" type="email"></label><label>Ghi chú <textarea id="booking-notes"></textarea></label><p>Thanh toán/đặt cọc online chỉ được bật sau khi phòng khám cấp cấu hình VNPay hoặc MoMo.</p><div class="nav"><button type="button" data-back>Quay lại</button><button id="booking-go">Gửi yêu cầu</button></div></section></form><p id="booking-message"></p><p><a href="my_appointments.php">Lịch hẹn của tôi</a></p></main>
<?php renderFooter(); ?>
<script>
const wizard=document.getElementById('booking-form'), steps=[...document.querySelectorAll('.s')], bars=[...document.querySelectorAll('.p span')], dateInput=document.getElementById('booking-date'), timeInput=document.getElementById('booking-time'), slotGrid=document.getElementById('slot-grid'), info=document.getElementById('slot-info'); let current=0;
function showStep(n){current=n;steps.forEach((x,i)=>x.classList.toggle('on',i===n));bars.forEach((x,i)=>x.classList.toggle('on',i===n));}
function stepValid(){if(current===0)return !!document.querySelector('[name=service]:checked');if(current===1)return !!dateInput.value&&!!timeInput.value;return true;}
document.querySelectorAll('[data-next]').forEach(x=>x.onclick=()=>stepValid()?showStep(current+1):alert('Vui lòng hoàn thành bước này.'));
document.querySelectorAll('[data-back]').forEach(x=>x.onclick=()=>showStep(current-1));
dateInput.onchange=async()=>{timeInput.value='';slotGrid.innerHTML='';info.textContent='Đang tải khung giờ…';try{const response=await fetch('booking_slots.php?date='+encodeURIComponent(dateInput.value));const data=await response.json();(data.slots||[]).forEach(slot=>{const button=document.createElement('button');button.type='button';button.textContent=slot.time;button.disabled=!slot.available;button.onclick=()=>{[...slotGrid.children].forEach(x=>x.style.background='');button.style.background='#dff4fb';timeInput.value=slot.time};slotGrid.append(button)});info.textContent='Giờ mờ đã kín.'}catch(e){info.textContent='Không tải được khung giờ. Vui lòng thử lại.'}};
wizard.onsubmit=async event=>{event.preventDefault();const selected=document.querySelector('[name=service]:checked'), phone=document.getElementById('booking-phone'), submit=document.getElementById('booking-go');if(!selected||!/^0\d{9}$/.test(phone.value)){alert('Kiểm tra dịch vụ và số điện thoại.');return;}submit.disabled=true;const payload={service:selected.value,category:selected.dataset.group,date:dateInput.value,time:timeInput.value,name:document.getElementById('booking-name').value.trim(),phone:phone.value,email:document.getElementById('booking-email').value.trim(),notes:document.getElementById('booking-notes').value.trim(),discount_code:document.getElementById('booking-code').value.trim()};try{const response=await fetch('book_appointment.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();document.getElementById('booking-message').textContent=data.success?'Đã giữ lịch #'+data.appointment_id+'. Phòng khám sẽ xác nhận lại.':data.message;if(data.success){wizard.reset();showStep(0)}}catch(e){document.getElementById('booking-message').textContent='Không kết nối được máy chủ.'}finally{submit.disabled=false}};
</script></body></html>
