<?php
session_start();
require_once 'config.php';
require_once 'content_repository.php';
if (($_SESSION['auth_user']['role'] ?? '') !== 'admin') { header('Location: auth.php'); exit; }
ensureContentSchema($conn);

function backToContentAdmin(): void { header('Location: content_admin.php?saved=1'); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    requireContentCsrf();
    $action = $_POST['action'] ?? '';
    if ($action === 'feedback_status') {
        $id=(int)($_POST['id']??0); $status=$_POST['status']??'pending';
        if (in_array($status,['pending','approved','rejected'],true)) { $s=$conn->prepare('UPDATE feedback SET status=? WHERE id=?'); $s->bind_param('si',$status,$id); $s->execute(); }
    } elseif ($action === 'faq_save') {
        $id=(int)($_POST['id']??0); $q=trim($_POST['question']??''); $a=trim($_POST['answer']??''); $o=(int)($_POST['sort_order']??0); $active=isset($_POST['is_active'])?1:0;
        if ($q!=='' && $a!=='') { if($id){$s=$conn->prepare('UPDATE faqs SET question=?,answer=?,sort_order=?,is_active=? WHERE id=?');$s->bind_param('ssiii',$q,$a,$o,$active,$id);}else{$s=$conn->prepare('INSERT INTO faqs(question,answer,sort_order,is_active) VALUES(?,?,?,?)');$s->bind_param('ssii',$q,$a,$o,$active);} $s->execute(); }
    } elseif ($action === 'faq_delete') { $id=(int)($_POST['id']??0); $s=$conn->prepare('DELETE FROM faqs WHERE id=?');$s->bind_param('i',$id);$s->execute();
    } elseif ($action === 'post_save') {
        $id=(int)($_POST['id']??0); $title=trim($_POST['title']??''); $slug=contentSlug($_POST['slug']?:$title); $excerpt=trim($_POST['excerpt']??''); $body=trim($_POST['content']??''); $image=trim($_POST['cover_image']??''); $category=trim($_POST['category']??''); $status=$_POST['status']==='published'?'published':'draft'; $published=$status==='published'?date('Y-m-d H:i:s'):null;
        if($title!==''){ if($id){$s=$conn->prepare('UPDATE blog_posts SET slug=?,title=?,excerpt=?,content=?,cover_image=?,category=?,status=?,published_at=COALESCE(published_at,?) WHERE id=?');$s->bind_param('ssssssssi',$slug,$title,$excerpt,$body,$image,$category,$status,$published,$id);}else{$s=$conn->prepare('INSERT INTO blog_posts(slug,title,excerpt,content,cover_image,category,status,published_at) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('ssssssss',$slug,$title,$excerpt,$body,$image,$category,$status,$published);} $s->execute(); }
    } elseif ($action === 'post_delete') { $id=(int)($_POST['id']??0);$s=$conn->prepare('DELETE FROM blog_posts WHERE id=?');$s->bind_param('i',$id);$s->execute();
    } elseif ($action === 'profile_save') {
        $uid=(int)($_POST['user_id']??0); $slug=contentSlug($_POST['slug']??''); $intro=trim($_POST['introduction']??'');$edu=trim($_POST['education']??'');$exp=trim($_POST['experience_text']??'');$cases=trim($_POST['case_count']??'');$note=trim($_POST['consultation_note']??'');$photo=trim($_POST['photo']??'');$pub=isset($_POST['is_published'])?1:0; $caseVal=$cases===''?null:(int)$cases;
        if($uid && $slug!==''){$s=$conn->prepare('INSERT INTO doctor_profiles(user_id,slug,introduction,education,experience_text,case_count,consultation_note,photo,is_published) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE slug=VALUES(slug),introduction=VALUES(introduction),education=VALUES(education),experience_text=VALUES(experience_text),case_count=VALUES(case_count),consultation_note=VALUES(consultation_note),photo=VALUES(photo),is_published=VALUES(is_published)');$s->bind_param('issssissi',$uid,$slug,$intro,$edu,$exp,$caseVal,$note,$photo,$pub);$s->execute();}
    } elseif ($action === 'term_save') {
        $id=(int)($_POST['id']??0);$pid=(int)($_POST['product_id']??0);$name=trim($_POST['service_name']??'');$priceNote=trim($_POST['price_note']??'');$warranty=trim($_POST['warranty_text']??'');$payment=trim($_POST['payment_note']??'');$order=(int)($_POST['sort_order']??0);$active=isset($_POST['is_active'])?1:0;
        if($name!==''){if($id){$s=$conn->prepare('UPDATE service_terms SET product_id=NULLIF(?,0),service_name=?,price_note=?,warranty_text=?,payment_note=?,sort_order=?,is_active=? WHERE id=?');$s->bind_param('issssiii',$pid,$name,$priceNote,$warranty,$payment,$order,$active,$id);}else{$s=$conn->prepare('INSERT INTO service_terms(product_id,service_name,price_note,warranty_text,payment_note,sort_order,is_active) VALUES(NULLIF(?,0),?,?,?,?,?,?)');$s->bind_param('issssii',$pid,$name,$priceNote,$warranty,$payment,$order,$active);} $s->execute();}
    } elseif ($action === 'term_delete') {$id=(int)($_POST['id']??0);$s=$conn->prepare('DELETE FROM service_terms WHERE id=?');$s->bind_param('i',$id);$s->execute();
    } elseif ($action === 'trust_save') {
        $id=(int)($_POST['id']??0);$type=in_array($_POST['item_type']??'', ['license','certificate','partner'],true)?$_POST['item_type']:'certificate';$title=trim($_POST['title']??'');$issuer=trim($_POST['issuer']??'');$code=trim($_POST['credential_code']??'');$url=trim($_POST['evidence_url']??'');$image=trim($_POST['image']??'');$desc=trim($_POST['description']??'');$verified=isset($_POST['is_verified'])?1:0;$public=isset($_POST['is_public'])?1:0;
        if($title!==''){if($id){$s=$conn->prepare('UPDATE trust_items SET item_type=?,title=?,issuer=?,credential_code=?,evidence_url=?,image=?,description=?,is_verified=?,is_public=? WHERE id=?');$s->bind_param('sssssssiii',$type,$title,$issuer,$code,$url,$image,$desc,$verified,$public,$id);}else{$s=$conn->prepare('INSERT INTO trust_items(item_type,title,issuer,credential_code,evidence_url,image,description,is_verified,is_public) VALUES(?,?,?,?,?,?,?,?,?)');$s->bind_param('sssssssii',$type,$title,$issuer,$code,$url,$image,$desc,$verified,$public);} $s->execute();}
    } elseif ($action === 'trust_delete') {$id=(int)($_POST['id']??0);$s=$conn->prepare('DELETE FROM trust_items WHERE id=?');$s->bind_param('i',$id);$s->execute();
    } elseif ($action === 'setting_save') {$key=$_POST['setting_key']??'';$value=trim($_POST['setting_value']??'');if($key==='google_reviews_embed_url'){$s=$conn->prepare('INSERT INTO site_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$s->bind_param('ss',$key,$value);$s->execute();}}
    backToContentAdmin();
}
$token=contentCsrfToken();
$feedback=contentRows($conn,"SELECT * FROM feedback ORDER BY id DESC LIMIT 30");
$faqs=contentRows($conn,"SELECT * FROM faqs ORDER BY sort_order,id");
$posts=contentRows($conn,"SELECT * FROM blog_posts ORDER BY updated_at DESC");
$doctors=contentRows($conn,"SELECT u.id,u.full_name,u.specialty,p.slug,p.introduction,p.education,p.experience_text,p.case_count,p.consultation_note,p.photo,p.is_published FROM users u LEFT JOIN doctor_profiles p ON p.user_id=u.id WHERE u.role='doctor' ORDER BY u.id");
$products=contentRows($conn,"SELECT id,name,price FROM products WHERE COALESCE(is_active,1)=1 ORDER BY name"); $terms=contentRows($conn,"SELECT * FROM service_terms ORDER BY sort_order,id"); $trust=contentRows($conn,"SELECT * FROM trust_items ORDER BY item_type,sort_order,id");
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quản trị nội dung | NALI</title><link rel="stylesheet" href="common.css"><link rel="stylesheet" href="clinic-ui.css"><link rel="stylesheet" href="content-pages.css"><style>.admin-content{max-width:1250px;margin:34px auto;padding:0 18px}.admin-content details{background:#fff;border:1px solid #d8e5eb;border-radius:14px;padding:14px 18px;margin:14px 0}.admin-content summary{cursor:pointer;font-weight:800;color:#17395d}.admin-content form{display:grid;gap:10px;margin:16px 0}.admin-content input,.admin-content textarea,.admin-content select{width:100%;padding:10px;border:1px solid #b8ccd5;border-radius:8px;font:inherit}.admin-content textarea{min-height:84px}.admin-content button{width:max-content;padding:9px 14px;border:0;border-radius:8px;background:#147db0;color:white;font-weight:700;cursor:pointer}.admin-content .danger{background:#b42318}.admin-content .row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.admin-content .list{border-top:1px solid #e6eef2;padding:12px 0}.admin-content small{color:#60717d}@media(max-width:700px){.admin-content .row{grid-template-columns:1fr}}</style></head><body>
<?php require_once 'includes/components.php'; renderHeader(); ?>
<main class="admin-content"><div class="content-actions"><a class="content-button secondary" href="admin_panel.php">← Bảng điều khiển</a><a class="content-button secondary" href="services.php">Xem website</a></div><h1>Quản trị nội dung & bằng chứng</h1><p>Chỉ xuất bản thông tin đã được phòng khám xác minh. Phản hồi chỉ hiện công khai sau khi duyệt.</p>
<details open><summary>Phản hồi khách hàng (<?=count($feedback)?> bản ghi gần nhất)</summary><?php foreach($feedback as $f): ?><div class="list"><b><?=htmlspecialchars($f['name'])?></b> · <?=str_repeat('★',(int)$f['rating'])?><br><small><?=htmlspecialchars($f['type']??'')?></small><p><?=nl2br(htmlspecialchars($f['message']??''))?></p><form method="post" style="display:flex;gap:8px;align-items:center"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="feedback_status"><input type="hidden" name="id" value="<?=$f['id']?>"><select name="status"><option value="pending" <?=$f['status']==='pending'?'selected':''?>>Chờ duyệt</option><option value="approved" <?=$f['status']==='approved'?'selected':''?>>Duyệt công khai</option><option value="rejected" <?=$f['status']==='rejected'?'selected':''?>>Từ chối</option></select><button>Lưu</button></form></div><?php endforeach; ?></details>
<details><summary>FAQ</summary><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="faq_save"><div class="row"><input name="question" placeholder="Câu hỏi" required><input type="number" name="sort_order" placeholder="Thứ tự" value="0"></div><textarea name="answer" placeholder="Câu trả lời đã được kiểm duyệt" required></textarea><label><input type="checkbox" name="is_active" checked> Hiển thị</label><button>Thêm FAQ</button></form><?php foreach($faqs as $f):?><div class="list"><b><?=htmlspecialchars($f['question'])?></b><p><?=htmlspecialchars($f['answer'])?></p><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="faq_delete"><input type="hidden" name="id" value="<?=$f['id']?>"><button class="danger">Xóa</button></form></div><?php endforeach;?></details>
<details><summary>Bài viết kiến thức</summary><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="post_save"><div class="row"><input name="title" placeholder="Tiêu đề" required><input name="slug" placeholder="Đường dẫn (tự tạo nếu để trống)"></div><div class="row"><input name="category" placeholder="Chuyên mục"><input name="cover_image" placeholder="Ảnh bìa, ví dụ images/...webp"></div><textarea name="excerpt" placeholder="Tóm tắt"></textarea><textarea name="content" placeholder="Nội dung bài viết đã được biên tập/chuyên môn duyệt"></textarea><select name="status"><option value="draft">Bản nháp</option><option value="published">Xuất bản</option></select><button>Lưu bài viết</button></form><?php foreach($posts as $p):?><div class="list"><b><?=htmlspecialchars($p['title'])?></b> <small>— <?=htmlspecialchars($p['status'])?></small><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="post_delete"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="danger">Xóa</button></form></div><?php endforeach;?></details>
<details><summary>Hồ sơ bác sĩ</summary><?php foreach($doctors as $d):?><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="profile_save"><input type="hidden" name="user_id" value="<?=$d['id']?>"><h3><?=htmlspecialchars($d['full_name'])?></h3><div class="row"><input name="slug" value="<?=htmlspecialchars($d['slug']??contentSlug($d['full_name']))?>" required><input name="photo" value="<?=htmlspecialchars($d['photo']??'')?>" placeholder="Ảnh đã có quyền sử dụng"></div><textarea name="introduction" placeholder="Giới thiệu"><?=htmlspecialchars($d['introduction']??'')?></textarea><textarea name="education" placeholder="Bằng cấp/chứng chỉ đã xác minh"><?=htmlspecialchars($d['education']??'')?></textarea><div class="row"><input name="experience_text" value="<?=htmlspecialchars($d['experience_text']??'')?>" placeholder="Kinh nghiệm đã xác minh"><input type="number" name="case_count" value="<?=htmlspecialchars((string)($d['case_count']??''))?>" placeholder="Số ca đã xác minh"></div><textarea name="consultation_note" placeholder="Ghi chú tư vấn/đặt lịch"><?=htmlspecialchars($d['consultation_note']??'')?></textarea><label><input type="checkbox" name="is_published" <?=$d['is_published']?'checked':''?>> Công khai hồ sơ</label><button>Lưu hồ sơ</button></form><?php endforeach;?></details>
<details><summary>Bảng giá, bảo hành & thanh toán</summary><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="term_save"><div class="row"><select name="product_id"><option value="0">Không liên kết dịch vụ</option><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['name'])?></option><?php endforeach;?></select><input name="service_name" placeholder="Tên mục hiển thị" required></div><input name="price_note" placeholder="Ghi chú giá (vd: giá tham khảo, xác nhận sau thăm khám)"><textarea name="warranty_text" placeholder="Chính sách bảo hành đã xác thực"></textarea><textarea name="payment_note" placeholder="Thanh toán/trả góp đã xác thực"></textarea><label><input type="checkbox" name="is_active" checked> Hiển thị</label><button>Lưu chính sách</button></form><?php foreach($terms as $t):?><div class="list"><b><?=htmlspecialchars($t['service_name'])?></b><p><?=htmlspecialchars($t['warranty_text']??'Chưa khai báo')?></p><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="term_delete"><input type="hidden" name="id" value="<?=$t['id']?>"><button class="danger">Xóa</button></form></div><?php endforeach;?></details>
<details><summary>Giấy phép, chứng nhận, đối tác</summary><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="trust_save"><div class="row"><select name="item_type"><option value="license">Giấy phép</option><option value="certificate">Chứng nhận</option><option value="partner">Đối tác</option></select><input name="title" placeholder="Tên giấy tờ/đối tác" required></div><div class="row"><input name="issuer" placeholder="Đơn vị cấp"><input name="credential_code" placeholder="Số hiệu (nếu được phép công bố)"></div><input name="evidence_url" placeholder="Liên kết bằng chứng/nguồn chính thức"><input name="image" placeholder="Ảnh quét/ảnh logo đã có quyền sử dụng"><textarea name="description" placeholder="Mô tả ngắn, không thêm tuyên bố chưa xác minh"></textarea><label><input type="checkbox" name="is_verified"> Đã xác minh</label><label><input type="checkbox" name="is_public"> Công khai</label><button>Lưu mục bằng chứng</button></form><?php foreach($trust as $t):?><div class="list"><b><?=htmlspecialchars($t['title'])?></b> <small><?=htmlspecialchars($t['item_type'])?> · <?=$t['is_verified']?'đã xác minh':'chưa xác minh'?> · <?=$t['is_public']?'công khai':'ẩn'?></small><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="trust_delete"><input type="hidden" name="id" value="<?=$t['id']?>"><button class="danger">Xóa</button></form></div><?php endforeach;?></details>
<details><summary>Google Reviews</summary><p>Chỉ dán URL nhúng (embed) lấy trực tiếp từ hồ sơ Google Business đã sở hữu/xác minh. Nếu để trống, website sẽ thông báo chưa liên kết thay vì giả đánh giá.</p><form method="post"><input type="hidden" name="csrf" value="<?=$token?>"><input type="hidden" name="action" value="setting_save"><input type="hidden" name="setting_key" value="google_reviews_embed_url"><input name="setting_value" value="<?=htmlspecialchars(contentSetting($conn,'google_reviews_embed_url'))?>" placeholder="https://www.google.com/maps/embed?..." type="url"><button>Lưu liên kết Google</button></form></details>
</main><?php renderFooter(); ?></body></html>
